CREATE DATABASE ConnectPlus;

USE ConnectPlus;

CREATE TABLE TipoContato(
	IdTipoContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT((NEWID())),
	Titulo VARCHAR(100) NOT NULL
);

CREATE TABLE Contato(
	IdContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT((NEWID())),
	Nome VARCHAR(150) NOT NULL,
	FormaContato VARCHAR(100) NOT NULL, 
	Imagem VARCHAR (255) NULL,

	--Importa a chave estrangeira
	IdTipoContato UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoContato(IdTipoContato)
);